### ISSUE TITLE
Overwrite Rec mode

### ISSUE THREAD

**Issue by midenok** [MockbaTheBorg/MockbaMod#2]
Despite there is Undo button I would prefer overwrite looped mode which does not require to press anything. Some people [agree](https://www.mpc-forums.com/viewtopic.php?p=1867482) with me.

**Comment by MockbaTheBorg** [comment]
I agree with you too. I find overdub only to be very limiting.
However that is Akai's functionality, to which we have no access. Or mod is not a different firmware, but the exact same Akai's MPC app running with a 'man in the middle' driver between it, the midi interface and the padboard.
Plus some scripts in the Linux which implement some additions.
Now, if Akai's firmware has quirks and limitations, MockbaMod will have the same. 
We can't modify the way Akai firmware works.
