### ISSUE TITLE
Dial knob speed in [shift + tempo] to change bpm

### ISSUE THREAD

**Issue by midenok** [MockbaTheBorg/MockbaMod#3]
When changing tempo dial knob speed is really dull: 1 full turn change is 20. Dial step should be 3 or 6 or even some acceleration algorithm applied. Shift function is really stupid: it changes hundredths which is just unuseful. Who dials hundredths for tempo?! Shift function should just lower dial step to 1.

**Comment by MockbaTheBorg** [comment]
Is this a MockbaMod issue or original firmware issue?

**Comment by midenok** [comment]
It is original firmware issue. Why do you want to close something that you don't know or don't want to implement? It may be fixed by someone else.

**Comment by MockbaTheBorg** [comment]
We cannot modify the way Akai firmware works, but in this specific one, as it is related to the communication between the padboard and the MPC app, we might be able to intercept and modify it, maybe sending multiple (or less) steps when shift is pressed. 
Changing hundreds makes no sense indeed. 
I will discuss the idea with the team.

**Comment by intelliriffer** [comment]
@midenok The Knob Ballistics and Response / Function is Something that is Programmed/Baked into Force Software (which we do not touch or modify).

Having Said that, Perhaps I can give some other Modifier a Try, Like if Navigate is Held, 1 Knob Movement Generates 10x pulses.. don't know if that will be productive or not, as all of these things need to be tested.. (hit and trial) . another Alternative could be to Have +/- button take on Modifiers and send Values x10,5 or whatever.. again I need to test out its feasibility before I can promise anything..  

Can you tell me on what screen are you changing the Tempo? 
Just so that we are on same page, as Tempo on Force can be changed different ways..

**Comment by intelliriffer** [comment]
@midenok are you modded already? I can send you latest compiled version of Midiloop to test.
Knob Ballistics as assumed, are controlled internally, so max boost I am getting now is about 4x / step even when setting it up to 10 or 20..  (Holding Select Button) Only that button nis feasible as it does not have any side effects)

However, the -/= Button Under the Knob Works Great on Steroids.. 
Here are new Settings customizable by end user..

KNOB-MULTIPLIER = 20 #Multipler to use for each jump of data dial usually only works for value of 4.
SELECT-PLUS-MINUS-MULTIPLIER = 50 # Multiplier to use for each press of + or - button with SELECT held
SHIFT-PLUS-MINUS-MULTIPLIER = 10 # Multiplier to use for each press of  + or - button with SHIFT held

These Work not only for Tempo but every where possible (where data dial or +- button change values) even  midi events. 
 
 https://youtu.be/PPPydouMcZ4

**Comment by midenok** [comment]
@intelliriffer Great! Holding Select is just fine!

> KNOB-MULTIPLIER = 20 #Multipler to use for each jump of data dial usually only works for value of 4.
SELECT-PLUS-MINUS-MULTIPLIER = 50 # Multiplier to use for each press of + or - button with SELECT held
SHIFT-PLUS-MINUS-MULTIPLIER = 10 # Multiplier to use for each press of + or - button with SHIFT held

Sorry, I don't understand. Does dial knob work with Select? I don't see that in the above settings. But +/- is not interesting, it is another control much worse than knob, so I never use it. Maybe +/- is good for precise changes (like it always were in all UI) but not vice versa.

**Comment by intelliriffer** [comment]
Are you using mockba mod already? I can send you files to check. and please come to discord.. 
polluting github issues serves no purpose out of context as these are not mod related issues..

**Comment by intelliriffer** [comment]
@midenok  here is the latest compiled Midiloop, the files go in your SDCARD/Addons/MidiLoop , backup older files just in case.
https://mega.nz/file/gp4TmRbK#9fl_Ksx_ujP7vqYyFEg_cUsMatl05m2TTutn92ytzuQ

I have noted that EDIT + Knob works better with tempo jumps..

here are new settings in config file :

SELECT-KNOB-MULTIPLIER = 33 #Multipler to use for each jump of data dial with SELECT Held  usually only works for value of 4.
EDIT-KNOB-MULTIPLIER = 10 #Multipler to use for each jump of data dial with Edit Held usually only works for value of 4.

SELECT-PLUS-MINUS-MULTIPLIER=50 # Multiplier to use for each press of + or - button with SELECT held

EDIT-PLUS-MINUS-MULTIPLIER = 16 #multipler to use with EDIT button held

SHIFT-PLUS-MINUS-MULTIPLIER=10 # Multiplier to use for each press of  + or - button with SHIFT held

**Comment by midenok** [comment]
Forwarded to manufacturer.
