### ISSUE TITLE
Hibernation

### ISSUE THREAD

**Issue by midenok** [MockbaTheBorg/MockbaMod#4]
Is it Linux? If so, maybe hibernation mode is possible. Loading large projects is really slow which is frustrating.

**Comment by MockbaTheBorg** [comment]
I am not sure if that specific Linux is able to do a full hibernation, bringing back display, padboard, etc.
This would need to be tested.

Let's bring features questions/requests to either Facebook or discord.

**Comment by midenok** [comment]
Of course it can. This is standard kernel feature. Sorry, I don't use facebook nor discord. And there may be people who find this project here like me (I found it through Google).

**Comment by MockbaTheBorg** [comment]
I can tell you that our discord channel is very much real time.
Questions you ask there are usually answered within minutes.
I understand you don't want to use Facebook or other social network, but in
the other hand we don't want to open yet a third channel for questions or
feature requests.
Then we would lose focus.
We do these things on our very, like VERY limited free time, but discord is
something that we keep open while at work.
Discord I look daily, Facebook maybe each other day, here I look maybe once
a month.

**Comment by MockbaTheBorg** [comment]
Regarding sleep mode. Akai can barely make work the things that are
supposed to work.
Waking the Force up means you have not only to bring back the motherboard,
but the padboard, which is an external board with its own CPU. The display
should come back, but it is not HDMI, it is a different protocol.
And the little displays over the knobs are yet another board, which I am
quite sure is USB.
"Of course it does" is related to the Linux, not the trinkets hanging on
the motherboard as external USB devices.
And on top of all that, Akai's MPC app needs to able to wake up, while
keeping everything in place.
Without finding a way to test it we cannot guarantee it will work.

**Comment by intelliriffer** [comment]
They can't even handle shutdown properly, systemd (poweroff) is totally skipped so can't even do a proper cleanup/housekeeping if one wants too. 
Its an embedded Linux and not all kernel extentions are supported/available by default.. Also there is a very aggressive process memory management running in background (RTLIMIT), no sure what impact hibernation brings on that as it needs swap and write caching..
as for sleep . it's already set : deep.

```
# cat /sys/power/mem_sleep 
s2idle [deep]

# cat /sys/power/state
freeze mem

```
as you can see above disk and standby states are not natively supported by the underlying system. Only freeze and mem..

**Comment by midenok** [comment]
> I can tell you that our discord channel is very much real time.

On the opposite, I do not need real time. I need unreal time!

> but in the other hand we don't want to open yet a third channel for questions or
feature requests. Then we would lose focus.

Please, you may not track requests here. Just let me write here.

**Comment by midenok** [comment]
> I can tell you that our discord channel is very much real time.

On the opposite, I do not need real time. I need unreal time!

> but in the other hand we don't want to open yet a third channel for questions or
feature requests. Then we would lose focus.

Please, you may not track requests here. Just let me write here.

> here I look maybe once a month.

That's very nice timeframe for me. What is the point in rushing somewhere?

> The display should come back, but it is not HDMI, it is a different protocol.

All modern bus: PCI, USB, I2C, etc are ACPI-compliant, so support suspend/resume. How it can be problem with display if it has no state (it has no its own memory)?

> And the little displays over the knobs are yet another board, which I am quite sure is USB.

These maybe have state, so the driver must update the state on resume. I guess these are standard linux devices, so everything should work fine. In the worst case they just won't display anything until touched.

> And on top of all that, Akai's MPC app needs to able to wake up, while keeping everything in place.

And it is normal OS process which means it is handled by the kernel properly. Do you think Akai wrote app in kernel space? That would be at least strange. I doubt they did anything in kernel space, not even drivers. No need and they don't have qualification for that.

**Comment by midenok** [comment]
> Without finding a way to test it we cannot guarantee it will work.

Linux was and is always weak on resume. Nobody guarantees anything!

> They can't even handle shutdown properly, systemd (poweroff) is totally skipped

Very well! I would skip that too on all my hosts if that would be easy. It is user-unfriendly thing trying to universalize everything with wrong defaults. It requires more time devotion than SysV for achieving same things. It is like XML -- looks like nice standard, but horrible to use.

> Its an embedded Linux and not all kernel extentions are supported/available by default.. Also there is a very aggressive process memory management running in background (RTLIMIT), 

Not a surprise according to their UI: they don't have "Back" button, every new window opens above all others.

> no sure what impact hibernation brings on that as it needs swap and write caching..

Yes, it needs swap partition or file, so scripts tweaking is required. Write caching? Why? What kind of? There is always fs write caching.

> as you can see above disk and standby states are not natively supported by the underlying system. Only freeze and mem..

They didn't compile that into kernel. Is there kernel config somewhere? `/proc/config`, `/boot/config`? It will not be easy to reverse-engineer kernel config. There are [some scripts](https://github.com/zznop/bn-kconfig-recover), but I don't believe they are 100% correct.

**Comment by intelliriffer** [comment]
you seem to have decent hold of linux system, 
MockbaMod/tkgl Mod Both give you full ssh access, please explore and discuss your findings in some appropriate discussion  system.

Again Github issues are to discuss problems related to MockbaMod or caused by it, not Akai Force or its subsystem in general.

**Comment by midenok** [comment]
@intelliriffer That doesn't matter where to discuss something. Look, this is of course your business, but you are trying to build system where is no need in any system. Ahh...
