### ISSUE TITLE
More chords in harmonize mode?

### ISSUE THREAD

**Issue by midenok** [MockbaTheBorg/MockbaMod#5]
[Shift + Note] -> TYPE: Harmonize; SCALE CHORD: 1-3-5, etc

There are so few chords... The list is so poor like someone just did it for f.ck off.

I'd like to see there intervals as well: 1-2, 1-3, 1-4, 1-5, 1-6, 1-7, 1-8, 1-9, 1-10.
Would be nice to have 7-chord without 3-rd or 5-th: 1-5-7, 1-5-7b, 1-3-7, 1-3-7b
SUS 7-chords? Inversions? 9-chords?

Yes, there are Chords mode, but it is kind of out-of-scale mode. And it has not so rich list as well...

**Comment by intelliriffer** [comment]
sorry cant keep answering features / discussions here.. please join discord..

**Comment by midenok** [comment]
Forwarded this FR to manufacturer
