### ISSUE TITLE
Question about Force display not working after boot

### ISSUE THREAD

**Issue by dolence** [MockbaTheBorg/MockbaMod#8]
Hey Mockba! 
I have a friend which his Force is showing the boot logo on display, pads light are on but after that it goes black. Unit seems to be functioning since he can load a project and play using buttons. Would a corrupted eMMC cause this? Any thoughts?

**Comment by MockbaTheBorg** [comment]
If the pads turn off their LEDs but are still functional it could be a
software problem.
The pads lights can be turned off.
Try reverting to the original Akai firmware and see if the problem
persists.
If it does, try Amit's emmc repair script.

Well, actually, try it regardless.

**Comment by MockbaTheBorg** [comment]
Did this work?
