### ISSUE TITLE
"Stop All" button doesn't work

### ISSUE THREAD

**Issue by sonejostudios** [MockbaTheBorg/MockbaMod#9]
Hi Devs,

for some reasons the "Stop All" button doesn't work on Mockba, but works fine if the force is launched without the SD card.
Maybe a midiloop bug or something similar due to the new hotkeys?

Just wanted to report.

Mockba 3.3.0.0

Cheers
Vince

**Comment by intelliriffer** [comment]
In your midiloop.config make sure you have  HW-STOP-ALL=STOP-ALL-CLIPS
This was added in a new version of Midoloop, you might be using older
config file, or forgot to update yours..
when you update midiloop via addon-manager , you config file is not updated, to avoid you losing changes, instead latest copy of config with version name is lie added and you can either copy that over to midiloop.config  (if you have not made any changes to yours) or compare and add changes manually..

It's should also be noted inside the release notes.txt file in your
Sdcard/AddOns/Midiloop folder..

**Comment by sonejostudios** [comment]
Oh great, I didn't notice it needs to be manually updated. Thanks!
